# Generated by Django 4.2.1 on 2023-07-20 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(max_length=10)),
                ('author', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=10)),
                ('resolved_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacation_start_date', models.DateField()),
                ('vacation_end_date', models.DateField()),
            ],
        ),
    ]
